system_resource_graph_python:
  type: task
  job:
    timing: 10m
    language: python
    logic_digest_id: 12597
    done_tags: systemgraphpy,sysokpy
    fail_tags: systemgraphfailpy
    threads: 1
    timeout: 60

queuetest_python:
  type: queue
  job:
    language: python
    logic_digest_id: 12598
    queue_tag:
      queue_tag: pythontest-work
      lookback: 5m
      lock_tag: pythontest-lock
      done_tags: pythontest-done
      fail_tags: pythontest-fail
      retry_failed: y
    threads: 2
    timeout: 300